version: "3"
services:
  natter-cf-origin:
    command: -e /opt/cf-origin.py -r
    volumes:
      - ./cf-origin.py:/opt/cf-origin.py
    environment:
      - TZ=Asia/Shanghai
    network_mode: host
    image: nattertool/natter
    restart: always
